### ISSUE TITLE
MBCS characters are garbled in title and list view

### ISSUE THREAD

**Issue by mchibams** [stephenegriffin/mfcmapi#246] opened 2018-12-05 05:00 UTC
When a string property such as PR_DISPLAY_NAME contains MBCS characters, the characters are garbled in Dialog Title and List view.
This causes stringTowstring() and LPCSTRToWstring() do not consider MBCS.
The functions should be as follows.

	std::wstring stringTowstring(const std::string& src)
	{
		std::wstring dst;
		int dstLen = MultiByteToWideChar(CP_ACP, 0, src.data(), (int) src.size(), NULL, 0);
		if (dstLen > 0)
		{
			std::vector<wchar_t> dstBuf(dstLen);
			if (MultiByteToWideChar(CP_ACP, 0, src.data(), (int) src.size(), &dstBuf[0], dstBuf.size()) == dstLen)
			{
				dst.assign(&dstBuf[0], dstLen);
			}
		}
		return dst;
	}

	std::wstring LPCSTRToWstring(LPCSTR src)
	{
		if (!src) return L"";
		std::string ansi = src;
		return stringTowstring(ansi);
	}

**Comment by stephenegriffin** [comment] 2018-12-05 18:18
This may not be addressable in the ansi builds  do you repro with a Unicode build of MFCMAPI? Also - can you share some sample strings I can test with?

**Comment by mchibams** [comment] 2018-12-06 00:51
This doesn't repro with a Unicode build of MFCMAPI, but released binaries in https://github.com/stephenegriffin/mfcmapi/releases/ seems to be ansi build.
So I hope the ansi build will be fixed.

Sample string is as follows;

Correct string:
Outlook データ ファイル

Garbled string:
Outlook ﾃfﾁ[ﾃ^ ﾃtﾃ@ﾃCﾃﾋ

The above string means "Outlook Data File" and this is default string for PST in Japanese version.

**Comment by stephenegriffin** [comment] 2018-12-18 01:41
Root cause looks more like this: https://stackoverflow.com/questions/9410681/setwindowtextw-in-an-ansi-project

**Comment by mchibams** [comment] 2018-12-18 02:05
I think the cause of the  problem in https://stackoverflow.com/questions/9410681/setwindowtextw-in-an-ansi-project is different.
When the non-ascii character turns to ?, it is caused passing wrong codepage to WideCharToMultiByte.

But the problem I've reported, MBCS characters are split two SBCS characters.

For example, the character code of "デ" is 0x8366 in Codepage 932 (Shift-JIS, the default codepage of Japanese), and it should be 0x30c7 in Unicode.
But stringTowstring handles the MBCS character as multiple SBCS characters, and just change the type from byte to word.
So the character "デ" becomes 0x0083 (â) and 0x0066 (f) in Unicode.

This may be OK in US-ASCII world, but it's NG in other language.

**Comment by mchibams** [comment] 2018-12-18 02:07
I think the cause of the  problem in https://stackoverflow.com/questions/9410681/setwindowtextw-in-an-ansi-project is different.
When the non-ascii character turns to ?, it is caused passing wrong codepage to WideCharToMultiByte.

But the problem I've reported, MBCS characters are split two SBCS characters.

For example, the character code of "デ" is 0x8366 in Codepage 932 (Shift-JIS, the default codepage of Japanese), and it should be 0x30c7 in Unicode.
But stringTowstring handles the MBCS character as multiple SBCS characters, and just change the type from byte to word.
So the character "デ" becomes 0x0083 (â) and 0x0066 (f) in Unicode.

This may be OK in US-ASCII world, but it's NG in other language.

**Comment by stephenegriffin** [comment] 2018-12-18 05:30
Yes - I'm familiar with the  round trip problem in conversion of MB text. That's why I overhauled the UI to keep strings Unicode native as much as possible even in the ascii builds.

However, the functions you identified aren't on the code path for setting or drawing the title here, so touching them won't fix the problem. The problem was exactly as identified in the SO article. Temp swapping in DefWindowProcW for Unicode handling of the message allows us to set the Unicode string without a round trip through ascii. Same trick in the drawing code allows us to get the native Unicode string without another round trip through ascii. So we can stay Unicode native all the way through.

Do let me know if you see any other scenarios where the UI shows ? for unicode characters. I can't fix PR_*_A strings - that conversion happens down in the MAPI layer. But I *can* ensure the rest of the UI uses _W props for data and avoids round trips through ascii.

**Closed** 2018-12-18 15:34 UTC
