### ISSUE TITLE
Large icons

### ISSUE THREAD

**Issue by danny030** [stephenegriffin/mfcmapi#30] opened 2017-03-01 09:04 UTC
Hi,

not sure, whether this is a bug or by design (skipped two years of development and moved from 15.0.0.1041 to 17.0.17033.02) but these large low-res icons are not looking very nice. Are they intended to look that way?

![image](https://cloud.githubusercontent.com/assets/26109035/23452732/accb4a0a-fe65-11e6-830d-273dab67505a.png)

**Comment by stephenegriffin** [comment] 2017-03-06 19:27
Duplicate of #29

**Closed by stephenegriffin** 2017-03-06 19:27 UTC
