### ISSUE TITLE
New Old Issue MAPI_E_FAILONEPROVIDER == 0x8004011D

### ISSUE THREAD

**Issue by Navoxctr** [stephenegriffin/mfcmapi#481] opened 2021-06-30 16:12 UTC
This issue seems to return every time there is an update to office. 

I managed to resolve it last time by a full office uninstall and reinstall.  This time I am unable to resolve it. 

Version of office installed.

Version 2105 (Build 14026.20308 Click-to-run)
Microsoft® Outlook® for Microsoft 365 MSO (16.0.14026.20294) 64-bit

Outlook is setup in Cached mode. Outlook mailbox is fully loaded.

I opened outlook to cache the creds (verified in credential manager) and then opened mfcmapi and still received this error.

Error:
Code: MAPI_E_FAILONEPROVIDER == 0x8004011D
Function lpSession->OpenMsgStore( ulUIParam, lpEID->cb, reinterpret_cast(lpEID->lpb), nullptr, ulFlags, static_cast<LPMDB*>(&lpMDB))
File D:\a\1\s\core\mapi\mapiStoreFunctions.cpp
Line 39

Is there anything else I need to configure in mfcmapi to resolve this? I use mfcmapi on a daily basis and love this tool I just need to know what I can do to resolve this short of going to find an older outlook 2013 client. I know it works with outlook 2013 connected to an o365 account.

**Comment by stephenegriffin** [comment] 2021-07-08 11:42
Dupe of #407

**Closed by stephenegriffin** 2021-07-08 11:42 UTC
