### ISSUE TITLE
App crash 

### ISSUE THREAD

**Issue by seang92** [stephenegriffin/mfcmapi#368] opened 2020-04-29 16:16 UTC
It opens fine but when i go to session- login it closes out (crashes).  I see info in the following in the event log:

Faulting application name: MFCMapi.exe, version: 20.0.20110.1, time stamp: 0x5e9d1acd
Faulting module name: KERNELBASE.dll, version: 10.0.18362.815, time stamp: 0x67005c2a
Exception code: 0xc06d007e
Fault offset: 0x00114402
Faulting process id: 0x3b04
Faulting application start time: 0x01d61e416bf0f3b7
Faulting application path: D:\Downloads\MFCMapi.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: dd86278f-6800-4db8-950f-6d5b90e9520a
Faulting package full name: 
Faulting package-relative application ID:

**Comment by stephenegriffin** [comment] 2020-04-29 19:30
Dupe of #367

**Closed by stephenegriffin** 2020-04-29 19:30 UTC

**Comment by seang92** [comment] 2020-04-30 15:22
I'm not really sure what i am supposed to do to fix this? Tried runing in cmd set PATH=C:\Program Files (x86)\Microsoft Office\root\Office16;C:\Program Files (x86)\Microsoft Office\root\vfs\ProgramFilesCommonX86\Microsoft Shared\OFFICE16;%PATH%, still nothing

**Comment by seang92** [comment] 2020-04-30 15:24
Version=1
EventType=APPCRASH
EventTime=132327337780982313
ReportType=2
Consent=1
UploadTime=132327337784772103
ReportStatus=268435456
ReportIdentifier=5ccfe0aa-63ee-45cc-b72c-053a4280b3e0
IntegratorReportIdentifier=8e42ef22-af91-4088-9263-43f6e159c87d
Wow64Host=34404
Wow64Guest=332
NsAppName=MFCMapi.exe
OriginalFilename=MFCMapi.EXE
AppSessionGuid=00001610-0001-00ea-9a10-8738031fd601
TargetAppId=W:0000cd2c229e0d6e66c7b75d6b48449011e000000904!000050357fcac8dc362115c0058165866129521e9a5a!MFCMapi.exe
TargetAppVer=2020//04//20:03:45:17!453bb1!MFCMapi.exe
BootId=4294967295
ServiceSplit=52682928
TargetAsId=6327
IsFatal=1
EtwNonCollectReason=1
Response.BucketId=8088047fcdfd6eda02a0b94ecc7729dc
Response.BucketTable=1
Response.LegacyBucketId=1342276437045357020
Response.type=4
Sig[0].Name=Application Name
Sig[0].Value=MFCMapi.exe
Sig[1].Name=Application Version
Sig[1].Value=20.0.20110.1
Sig[2].Name=Application Timestamp
Sig[2].Value=5e9d1acd
Sig[3].Name=Fault Module Name
Sig[3].Value=KERNELBASE.dll
Sig[4].Name=Fault Module Version
Sig[4].Value=10.0.18362.815
Sig[5].Name=Fault Module Timestamp
Sig[5].Value=67005c2a
Sig[6].Name=Exception Code
Sig[6].Value=c06d007e
Sig[7].Name=Exception Offset
Sig[7].Value=00114402
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=10.0.18363.2.0.0.256.48
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=1033
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=2beb
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=2beba6fb4680d73a8c78ca7c24ccdb46
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=ff77
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=ff7714ec4afcc5465994d79f4a396c0a
UI[2]=D:\Downloads\MFCMapi.exe
LoadedModule[0]=D:\Downloads\MFCMapi.exe
LoadedModule[1]=C:\WINDOWS\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\WINDOWS\System32\KERNEL32.DLL
LoadedModule[3]=C:\WINDOWS\System32\KERNELBASE.dll
LoadedModule[4]=C:\WINDOWS\System32\USER32.dll
LoadedModule[5]=C:\WINDOWS\System32\win32u.dll
LoadedModule[6]=C:\WINDOWS\System32\GDI32.dll
LoadedModule[7]=C:\WINDOWS\System32\gdi32full.dll
LoadedModule[8]=C:\WINDOWS\System32\msvcp_win.dll
LoadedModule[9]=C:\WINDOWS\System32\ucrtbase.dll
LoadedModule[10]=C:\WINDOWS\System32\COMDLG32.dll
LoadedModule[11]=C:\WINDOWS\System32\msvcrt.dll
LoadedModule[12]=C:\WINDOWS\System32\combase.dll
LoadedModule[13]=C:\WINDOWS\System32\RPCRT4.dll
LoadedModule[14]=C:\WINDOWS\System32\SspiCli.dll
LoadedModule[15]=C:\WINDOWS\System32\CRYPTBASE.dll
LoadedModule[16]=C:\WINDOWS\System32\bcryptPrimitives.dll
LoadedModule[17]=C:\WINDOWS\System32\sechost.dll
LoadedModule[18]=C:\WINDOWS\SYSTEM32\MSIMG32.dll
LoadedModule[19]=C:\WINDOWS\System32\shcore.dll
LoadedModule[20]=C:\WINDOWS\System32\SHLWAPI.dll
LoadedModule[21]=C:\WINDOWS\System32\SHELL32.dll
LoadedModule[22]=C:\WINDOWS\System32\cfgmgr32.dll
LoadedModule[23]=C:\WINDOWS\System32\windows.storage.dll
LoadedModule[24]=C:\WINDOWS\System32\advapi32.dll
LoadedModule[25]=C:\WINDOWS\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.18362.815_none_2e70f018278c27fa\COMCTL32.dll
LoadedModule[26]=C:\WINDOWS\System32\profapi.dll
LoadedModule[27]=C:\WINDOWS\System32\powrprof.dll
LoadedModule[28]=C:\WINDOWS\System32\UMPDC.dll
LoadedModule[29]=C:\WINDOWS\System32\kernel.appcore.dll
LoadedModule[30]=C:\WINDOWS\System32\cryptsp.dll
LoadedModule[31]=C:\WINDOWS\System32\ole32.dll
LoadedModule[32]=C:\WINDOWS\System32\OLEAUT32.dll
LoadedModule[33]=C:\WINDOWS\SYSTEM32\UxTheme.dll
LoadedModule[34]=C:\WINDOWS\System32\IMM32.dll
LoadedModule[35]=C:\WINDOWS\SYSTEM32\OLEACC.dll
LoadedModule[36]=C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
LoadedModule[37]=C:\WINDOWS\WinSxS\x86_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.18362.815_none_5f5be2fd821ea1c8\gdiplus.dll
LoadedModule[38]=C:\WINDOWS\System32\bcrypt.dll
LoadedModule[39]=C:\WINDOWS\SYSTEM32\PROPSYS.dll
LoadedModule[40]=C:\WINDOWS\SYSTEM32\WINMM.dll
LoadedModule[41]=C:\WINDOWS\SYSTEM32\VERSION.dll
LoadedModule[42]=C:\WINDOWS\SYSTEM32\WINMMBASE.dll
LoadedModule[43]=C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
LoadedModule[44]=C:\WINDOWS\System32\tmumh\20019\AddOn\8.20.0.1030\TmUmEvt.dll
LoadedModule[45]=C:\WINDOWS\System32\PSAPI.DLL
LoadedModule[46]=C:\WINDOWS\System32\tmumh\20019\TmMon\2.7.3.1026\tmmon.dll
LoadedModule[47]=C:\WINDOWS\system32\riched20.dll
LoadedModule[48]=C:\WINDOWS\SYSTEM32\USP10.dll
LoadedModule[49]=C:\WINDOWS\SYSTEM32\msls31.dll
LoadedModule[50]=C:\WINDOWS\system32\rundll32.exe
LoadedModule[51]=C:\WINDOWS\system32\aclui.dll
LoadedModule[52]=C:\WINDOWS\SYSTEM32\NTDSAPI.dll
LoadedModule[53]=C:\WINDOWS\System32\WS2_32.dll
LoadedModule[54]=C:\WINDOWS\SYSTEM32\XmlLite.dll
LoadedModule[55]=C:\WINDOWS\system32\msi.dll
LoadedModule[56]=C:\WINDOWS\System32\MSCTF.dll
LoadedModule[57]=C:\WINDOWS\SYSTEM32\TextInputFramework.dll
LoadedModule[58]=C:\WINDOWS\SYSTEM32\CoreUIComponents.dll
LoadedModule[59]=C:\WINDOWS\SYSTEM32\CoreMessaging.dll
LoadedModule[60]=C:\WINDOWS\SYSTEM32\ntmarta.dll
LoadedModule[61]=C:\WINDOWS\SYSTEM32\wintypes.dll
LoadedModule[62]=C:\WINDOWS\SYSTEM32\iertutil.dll
LoadedModule[63]=C:\WINDOWS\SYSTEM32\srpapi.dll
LoadedModule[64]=C:\WINDOWS\System32\CRYPT32.dll
LoadedModule[65]=C:\WINDOWS\System32\MSASN1.dll
LoadedModule[66]=C:\WINDOWS\SYSTEM32\MSFTEDIT.DLL
LoadedModule[67]=C:\WINDOWS\System32\clbcatq.dll
LoadedModule[68]=C:\Windows\System32\Windows.Globalization.dll
LoadedModule[69]=C:\Windows\System32\Bcp47Langs.dll
LoadedModule[70]=C:\Windows\System32\bcp47mrm.dll
LoadedModule[71]=C:\WINDOWS\SYSTEM32\globinputhost.dll
LoadedModule[72]=C:\WINDOWS\system32\dataexchange.dll
LoadedModule[73]=C:\WINDOWS\system32\d3d11.dll
LoadedModule[74]=C:\WINDOWS\system32\dcomp.dll
LoadedModule[75]=C:\WINDOWS\system32\dxgi.dll
LoadedModule[76]=C:\WINDOWS\SYSTEM32\dxcore.dll
LoadedModule[77]=C:\WINDOWS\system32\twinapi.appcore.dll
LoadedModule[78]=C:\WINDOWS\system32\RMCLIENT.dll
LoadedModule[79]=C:\Program Files (x86)\Microsoft Office\root\VFS\ProgramFilesCommonX86\system\msmapi\1033\msmapi32.dll
LoadedModule[80]=C:\WINDOWS\SYSTEM32\VCRUNTIME140.dll
LoadedModule[81]=C:\Program Files (x86)\Microsoft Office\root\Office16\JitV.dll
LoadedModule[82]=C:\Program Files (x86)\Microsoft Office\root\Office16\AppvIsvSubsystems32.dll
LoadedModule[83]=C:\Program Files (x86)\Microsoft Office\root\Office16\c2r32.dll
LoadedModule[84]=C:\WINDOWS\SYSTEM32\USERENV.dll
LoadedModule[85]=C:\Program Files (x86)\Microsoft Office\root\Office16\olmapi32.dll
LoadedModule[86]=C:\WINDOWS\SYSTEM32\WTSAPI32.dll
LoadedModule[87]=C:\WINDOWS\SYSTEM32\wevtapi.dll
LoadedModule[88]=C:\Program Files (x86)\Microsoft Office\root\Office16\MSVCP140.dll
State[0].Key=Transport.DoneStage1
State[0].Value=1
OsInfo[0].Key=vermaj
OsInfo[0].Value=10
OsInfo[1].Key=vermin
OsInfo[1].Value=0
OsInfo[2].Key=verbld
OsInfo[2].Value=18363
OsInfo[3].Key=ubr
OsInfo[3].Value=815
OsInfo[4].Key=versp
OsInfo[4].Value=0
OsInfo[5].Key=arch
OsInfo[5].Value=9
OsInfo[6].Key=lcid
OsInfo[6].Value=1033
OsInfo[7].Key=geoid
OsInfo[7].Value=244
OsInfo[8].Key=sku
OsInfo[8].Value=48
OsInfo[9].Key=domain
OsInfo[9].Value=1
OsInfo[10].Key=prodsuite
OsInfo[10].Value=256
OsInfo[11].Key=ntprodtype
OsInfo[11].Value=1
OsInfo[12].Key=platid
OsInfo[12].Value=10
OsInfo[13].Key=sr
OsInfo[13].Value=0
OsInfo[14].Key=tmsi
OsInfo[14].Value=365684
OsInfo[15].Key=osinsty
OsInfo[15].Value=1
OsInfo[16].Key=iever
OsInfo[16].Value=11.778.18362.0-11.0.185
OsInfo[17].Key=portos
OsInfo[17].Value=0
OsInfo[18].Key=ram
OsInfo[18].Value=32691
OsInfo[19].Key=svolsz
OsInfo[19].Value=475
OsInfo[20].Key=wimbt
OsInfo[20].Value=0
OsInfo[21].Key=blddt
OsInfo[21].Value=190318
OsInfo[22].Key=bldtm
OsInfo[22].Value=1202
OsInfo[23].Key=bldbrch
OsInfo[23].Value=19h1_release
OsInfo[24].Key=bldchk
OsInfo[24].Value=0
OsInfo[25].Key=wpvermaj
OsInfo[25].Value=0
OsInfo[26].Key=wpvermin
OsInfo[26].Value=0
OsInfo[27].Key=wpbuildmaj
OsInfo[27].Value=0
OsInfo[28].Key=wpbuildmin
OsInfo[28].Value=0
OsInfo[29].Key=osver
OsInfo[29].Value=10.0.18362.815.amd64fre.19h1_release.190318-1202
OsInfo[30].Key=buildflightid
OsInfo[30].Value=91712D02-7DCF-478A-ACFC-6E4C474FC754.1
OsInfo[31].Key=edition
OsInfo[31].Value=Professional
OsInfo[32].Key=ring
OsInfo[33].Key=expid
OsInfo[34].Key=containerid
OsInfo[35].Key=containertype
OsInfo[36].Key=edu
OsInfo[36].Value=0
FriendlyEventName=Stopped working
ConsentKey=APPCRASH
AppName=MFCMAPI Unicode x86
AppPath=D:\Downloads\MFCMapi.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=50F9CEA7AD903AC299F5408A64EB4519
MetadataHash=2008839034

**Comment by stephenegriffin** [comment] 2020-05-01 01:53
The fix will be to update outlook when the fix for outlook comes out, which should be soon. Until then you can use the path workaround. Please continue discussion over in #367 if you still need help.
